secretGenerator:
- name: mysql-root-pass
  literals:
  - password=R00t
- name: mysql-user-pass
  literals:
  - username=spring
  - password=bitc5600
- name: mysql-db-url
  literals:
  - database=spring
  - url=jdbc:mysql://charting-app-mysql:3306/spring?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
resources:
  - mysql-deployment.yaml
  - charting-app-server.yaml
  - charting-app-client.yaml
